name: Build and test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-22.04    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Npm CI
        run: npm ci
      - name: Build
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e:ci